### ISSUE TITLE
Javascript not connected with html

### ISSUE THREAD

**Issue by parikshit245** [parikshit245/dice-game#4]
Description: Javasript is not connected with html, go to html and figure out how to connect it with html

**Comment by anisriaz** [comment]
To connect JavaScript with HTML, make sure you include your JavaScript file (script.js) within a <script> tag in your HTML file, like this:

<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <script src="script.js"></script>
</body>
</html>
